// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU0z7u5QGRg5fpIiR3UoeHdF_mLxtrMJo',
    appId: '1:811457355325:web:dd32e238a93cf08339d454',
    messagingSenderId: '811457355325',
    projectId: 'family-job-board',
    authDomain: 'family-job-board.firebaseapp.com',
    storageBucket: 'family-job-board.appspot.com',
    measurementId: 'G-RCFX5H8Y3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABPHew_fZQlAzn3miY2mUtrsoOi2rXMTE',
    appId: '1:811457355325:android:dc95ffbbecee286339d454',
    messagingSenderId: '811457355325',
    projectId: 'family-job-board',
    storageBucket: 'family-job-board.appspot.com',
  );
}
